version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: todo-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: todo_list_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
